"""Public config surface preserved for existing phase1 imports."""

from phase1.config.asr import (
    ASR_BATCH_SIZE,
    ASR_THREADS,
    ASR_VAD_CHUNK_SIZE,
    ASR_VAD_METHOD,
    resolve_asr_batch_size,
    resolve_asr_settings,
    resolve_asr_threads,
    resolve_asr_vad_chunk_size,
    resolve_asr_vad_method,
)
from phase1.config.env import BASE_DIR, MODELS_DIR
from phase1.config.models import (
    DEFAULT_DETECT_MODEL,
    HF_HUB_OFFLINE,
    HF_TOKEN,
    LANG_MODEL_MAP,
    PYANNOTE_DIARIZATION_MODEL,
    PYANNOTE_SEGMENTATION_MODEL,
    SUPPORTED_LANGS,
    TRANSFORMERS_OFFLINE,
    WHISPER_MODEL_OVERRIDE,
    resolve_detect_model,
    resolve_lang_model_map,
    resolve_whisper_model_override,
)
from phase1.config.runtime import (
    COMPUTE_TYPE,
    DEVICE,
    DIARIZE_COMPUTE_TYPE,
    DIARIZE_DEVICE,
    cpu_core_count,
    get_alignment_runtime_config,
    get_asr_runtime_config,
    get_diarization_runtime_config,
    requested_alignment_device,
    requested_asr_device,
    requested_diarization_device,
)

__all__ = [
    "ASR_BATCH_SIZE",
    "ASR_THREADS",
    "ASR_VAD_CHUNK_SIZE",
    "ASR_VAD_METHOD",
    "resolve_asr_batch_size",
    "resolve_asr_threads",
    "resolve_asr_vad_chunk_size",
    "resolve_asr_vad_method",
    "resolve_asr_settings",
    "BASE_DIR",
    "MODELS_DIR",
    "HF_TOKEN",
    "HF_HUB_OFFLINE",
    "TRANSFORMERS_OFFLINE",
    "WHISPER_MODEL_OVERRIDE",
    "PYANNOTE_DIARIZATION_MODEL",
    "PYANNOTE_SEGMENTATION_MODEL",
    "LANG_MODEL_MAP",
    "DEFAULT_DETECT_MODEL",
    "SUPPORTED_LANGS",
    "resolve_detect_model",
    "resolve_lang_model_map",
    "resolve_whisper_model_override",
    "DEVICE",
    "DIARIZE_DEVICE",
    "COMPUTE_TYPE",
    "DIARIZE_COMPUTE_TYPE",
    "cpu_core_count",
    "get_asr_runtime_config",
    "get_alignment_runtime_config",
    "get_diarization_runtime_config",
    "requested_asr_device",
    "requested_alignment_device",
    "requested_diarization_device",
]
